import { DatabaseSchema } from "@/types/schema";

export const DEFAULT_SAMPLE_SCHEMA: DatabaseSchema = {
  tables: [
    {
      id: "table-user",
      name: "User",
      description: "Application users and authentication profiles",
      position: { x: 50, y: 100 },
      columns: [
        { name: "id", type: "cuid", isPrimaryKey: true },
        { name: "username", type: "String", isUnique: true, isNullable: true },
        { name: "name", type: "String", isNullable: true },
        { name: "email", type: "String", isUnique: true },
        { name: "userRole", type: "Enum" },
        { name: "creditBalance", type: "Int", defaultValue: 50 },
        { name: "createdAt", type: "DateTime" },
        { name: "updatedAt", type: "DateTime" },
      ],
    },
    {
      id: "table-repo",
      name: "Repo",
      description: "Connected Git repositories and ingestion state",
      position: { x: 420, y: 50 },
      columns: [
        { name: "id", type: "cuid", isPrimaryKey: true },
        { name: "name", type: "String" },
        {
          name: "userId",
          type: "String",
          isForeignKey: true,
          references: { targetTable: "User", targetColumn: "id" },
        },
        { name: "url", type: "String" },
        { name: "branch", type: "String", defaultValue: "main" },
        { name: "status", type: "Enum" },
        { name: "createdAt", type: "DateTime" },
      ],
    },
    {
      id: "table-chat",
      name: "Chat",
      description: "Chat sessions associated with repositories",
      position: { x: 420, y: 420 },
      columns: [
        { name: "id", type: "cuid", isPrimaryKey: true },
        { name: "title", type: "String", isNullable: true },
        {
          name: "userId",
          type: "String",
          isForeignKey: true,
          references: { targetTable: "User", targetColumn: "id" },
        },
        {
          name: "repoId",
          type: "String",
          isForeignKey: true,
          references: { targetTable: "Repo", targetColumn: "id" },
        },
        { name: "createdAt", type: "DateTime" },
      ],
    },
    {
      id: "table-message",
      name: "Message",
      description: "Conversation history and LLM context",
      position: { x: 800, y: 420 },
      columns: [
        { name: "id", type: "cuid", isPrimaryKey: true },
        {
          name: "chatId",
          type: "String",
          isForeignKey: true,
          references: { targetTable: "Chat", targetColumn: "id" },
        },
        { name: "role", type: "Enum" },
        { name: "content", type: "String" },
        { name: "context", type: "Json", isNullable: true },
        { name: "createdAt", type: "DateTime" },
      ],
    },
    {
      id: "table-repo-analysis",
      name: "RepoAnalysis",
      description: "Parsed endpoints and page metadata",
      position: { x: 800, y: 70 },
      columns: [
        { name: "id", type: "uuid", isPrimaryKey: true },
        {
          name: "repoId",
          type: "String",
          isForeignKey: true,
          isUnique: true,
          references: { targetTable: "Repo", targetColumn: "id" },
        },
        { name: "apis", type: "Json" },
        { name: "pages", type: "Json" },
        { name: "createdAt", type: "DateTime" },
      ],
    },
  ],
  relations: [
    {
      id: "rel-user-repo",
      sourceTable: "User",
      sourceColumn: "id",
      targetTable: "Repo",
      targetColumn: "userId",
      cardinality: "one-to-many",
      label: "1:N",
    },
    {
      id: "rel-user-chat",
      sourceTable: "User",
      sourceColumn: "id",
      targetTable: "Chat",
      targetColumn: "userId",
      cardinality: "one-to-many",
      label: "1:N",
    },
    {
      id: "rel-repo-chat",
      sourceTable: "Repo",
      sourceColumn: "id",
      targetTable: "Chat",
      targetColumn: "repoId",
      cardinality: "one-to-many",
      label: "1:N",
    },
    {
      id: "rel-chat-message",
      sourceTable: "Chat",
      sourceColumn: "id",
      targetTable: "Message",
      targetColumn: "chatId",
      cardinality: "one-to-many",
      label: "1:N",
    },
    {
      id: "rel-repo-analysis",
      sourceTable: "Repo",
      sourceColumn: "id",
      targetTable: "RepoAnalysis",
      targetColumn: "repoId",
      cardinality: "one-to-one",
      label: "1:1",
    },
  ],
};
